# Generated by Django 4.2.27 on 2026-03-18 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for this translation.', primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Short unique reference code for this translation (auto-generated).', max_length=20, unique=True)),
                ('field_name', models.CharField(help_text='Name of the translated field, for example title, description, or content.', max_length=100)),
                ('source_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], help_text='Language code of the original text.', max_length=10)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese')], help_text='Language code of the translated text.', max_length=10)),
                ('original_text', models.TextField(help_text='Original source text before translation.')),
                ('translated_text', models.TextField(help_text='Final translated text stored for display or use.')),
                ('intended_text', models.TextField(help_text='Intended phrasing or translation guidance for the target language.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Project this translation belongs to, if the translated content is project-level.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='Task this translation belongs to, if the translated content is task-level.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'db_table': 'translations',
                'indexes': [models.Index(fields=['project_id'], name='translation_project_a9837a_idx'), models.Index(fields=['task_id'], name='translation_task_id_9ae74a_idx'), models.Index(fields=['source_language', 'target_language'], name='translation_source__8f4214_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('project_id', 'field_name', 'target_language'), name='uniq_translation_project_field_target_lang'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('task_id', 'field_name', 'target_language'), name='uniq_translation_task_field_target_lang'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('project__isnull', False), ('task__isnull', True)), models.Q(('project__isnull', True), ('task__isnull', False)), _connector='OR'), name='translation_requires_exactly_one_scope'),
        ),
    ]
