# Generated by Django 4.2.27 on 2026-05-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_report_status'),
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translation',
            name='translation_requires_exactly_one_scope',
        ),
        migrations.AddField(
            model_name='translation',
            name='report',
            field=models.ForeignKey(blank=True, help_text='Report this translation belongs to, if the translated content is report-level.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.report'),
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['report_id'], name='translation_report__0676d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('report_id', 'field_name', 'target_language'), name='uniq_translation_report_field_target_lang'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('project__isnull', False), ('task__isnull', True), ('report__isnull', True)), models.Q(('project__isnull', True), ('task__isnull', False), ('report__isnull', True)), models.Q(('project__isnull', True), ('task__isnull', True), ('report__isnull', False)), _connector='OR'), name='translation_requires_exactly_one_scope'),
        ),
    ]
