# Generated by Django 4.2.27 on 2026-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_remove_translation_translation_requires_exactly_one_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='scope',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('task', 'Task'), ('report', 'Report')], db_index=True, help_text='Type of entity being translated.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='scope_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the translated entity.', null=True),
        ),
    ]
