# Generated by Django 4.2.27 on 2026-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_backfill_translation_scope'),
    ]

    operations = [
        # ----------------------------------------------------
        # 1. DROP OLD FK-BASED UNIQUE CONSTRAINTS
        # ----------------------------------------------------
        migrations.RemoveConstraint(
            model_name="translation",
            name="uniq_translation_project_field_target_lang",
        ),
        migrations.RemoveConstraint(
            model_name="translation",
            name="uniq_translation_task_field_target_lang",
        ),
        migrations.RemoveConstraint(
            model_name="translation",
            name="uniq_translation_report_field_target_lang",
        ),

        # ----------------------------------------------------
        # 2. DROP OLD CHECK CONSTRAINT
        # ----------------------------------------------------
        migrations.RemoveConstraint(
            model_name="translation",
            name="translation_requires_exactly_one_scope",
        ),

        # ----------------------------------------------------
        # 3. DROP OLD INDEXES (FK-based)
        # IMPORTANT: ensure these names match your DB exactly
        # ----------------------------------------------------
        migrations.RemoveIndex(
            model_name="translation",
            name="translation_project_a9837a_idx",
        ),
        migrations.RemoveIndex(
            model_name="translation",
            name="translation_task_id_9ae74a_idx",
        ),
        migrations.RemoveIndex(
            model_name="translation",
            name="translation_report__0676d3_idx",
        ),

        # ----------------------------------------------------
        # 4. REMOVE LEGACY FK COLUMNS (CRITICAL STEP)
        # ----------------------------------------------------
        migrations.RemoveField(
            model_name="translation",
            name="project",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="task",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="report",
        ),

        # ----------------------------------------------------
        # 5. ENFORCE NEW SCHEMA (scope system)
        # ----------------------------------------------------
        migrations.AlterField(
            model_name="translation",
            name="scope",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("project", "Project"),
                    ("task", "Task"),
                    ("report", "Report"),
                ],
                db_index=True,
                help_text="Type of entity being translated.",
            ),
        ),

        migrations.AlterField(
            model_name="translation",
            name="scope_id",
            field=models.UUIDField(
                db_index=True,
                help_text="UUID of the translated entity.",
            ),
        ),

        # ----------------------------------------------------
        # 6. NEW OPTIMIZED INDEX (REPLACEMENT FOR FK INDEXES)
        # ----------------------------------------------------
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["scope", "scope_id"],
                name="translation_scope_c4e8a7_idx",
            ),
        ),

        # ----------------------------------------------------
        # 7. FINAL UNIQUE CONSTRAINT (NEW SYSTEM ONLY)
        # ----------------------------------------------------
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=[
                    "scope",
                    "scope_id",
                    "field_name",
                    "target_language",
                ],
                name="uniq_translation_scope_field_target_lang",
            ),
        ),
    ]
