# Generated by Django 4.2.27 on 2026-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_remove_translation_uniq_translation_project_field_target_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='scope',
            field=models.CharField(choices=[('project', 'Project'), ('task', 'Task'), ('report', 'Report'), ('task_comment', 'Task Comment'), ('report_comment', 'Report Comment')], db_index=True, help_text='Type of entity being translated.', max_length=20),
        ),
    ]
