# Generated by Django 4.2.27 on 2026-02-21 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_status'),
        ('projectMembers', '0002_alter_projectmember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_remove_organization_unique_organization_name_per_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('expected_hours', models.DecimalField(decimal_places=1, max_digits=6)),
                ('status', models.CharField(choices=[('backlog', 'backlog'), ('ready', 'ready'), ('in_progress', 'in_progress'), ('blocked', 'blocked'), ('review', 'review'), ('testing', 'testing'), ('done', 'done'), ('deployed', 'deployed'), ('cancelled', 'cancelled')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='projectMembers.projectmember')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to='projectMembers.projectmember')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'status'], name='tasks_organis_6a5e2b_idx'), models.Index(fields=['project', 'status'], name='tasks_project_fe19a5_idx'), models.Index(fields=['assigned_to', 'status'], name='tasks_assigne_801c9d_idx'), models.Index(fields=['reported_by'], name='tasks_reporte_babc80_idx'), models.Index(fields=['due_date'], name='tasks_due_dat_0359a9_idx')],
            },
        ),
    ]
