# Generated by Django 4.2.27 on 2026-04-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectMembers', '0002_alter_projectmember_status'),
        ('organizations', '0005_alter_membership_preferred_language'),
        ('tasks', '0004_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='projectMembers.projectmember'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='organizations.organization'),
        ),
    ]
