# Generated by Django 4.2.27 on 2026-05-11 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0005_alter_membership_preferred_language"),
        ("projectMembers", "0002_alter_projectmember_status"),
        ("tasks", "0005_alter_taskcomment_membership_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="is_deleted")),
                ("is_archived", models.BooleanField(default=False, verbose_name="is_archived")),
                ("is_archived_at", models.DateTimeField(blank=True, null=True, verbose_name="is_archived_at")),
                ("is_deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="is_deleted_at")),
                ("is_archived_reason", models.TextField(blank=True, default="", verbose_name="is_archived_reason")),
                ("is_deleted_reason", models.TextField(blank=True, default="", verbose_name="is_deleted_reason")),
                ("is_archived_by_email", models.CharField(blank=True, default="", max_length=100, verbose_name="is_archived_by")),
                ("is_deleted_by_email", models.CharField(blank=True, default="", max_length=100, verbose_name="is_deleted_by")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("link", "Link")], default="link", max_length=20)),
                ("url", models.URLField(max_length=2048)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("membership", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_attachments", to="projectMembers.projectmember")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="task_attachments", to="organizations.organization")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="tasks.task")),
            ],
            options={
                "db_table": "task_attachments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["task"], name="task_attach_task_id_637c08_idx"),
                    models.Index(fields=["organisation"], name="task_attach_organis_f1fbd5_idx"),
                    models.Index(fields=["created_at"], name="task_attach_created_5d0c1e_idx"),
                ],
            },
        ),
    ]
