# Generated by Django 4.2.27 on 2026-05-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskattachment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='taskattachment',
            name='task_attach_task_id_637c08_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskattachment',
            name='task_attach_organis_f1fbd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskattachment',
            name='task_attach_created_5d0c1e_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('improvement', 'Improvement'), ('documentation', 'Documentation'), ('other', 'Other')], default='feature', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='type',
            field=models.CharField(choices=[('github', 'GitHub'), ('file', 'File'), ('link', 'Link'), ('document', 'Document')], default='link', max_length=20),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task', 'is_deleted'], name='task_attach_task_id_c0269b_idx'),
        ),
    ]
