# Generated by Django 4.2.27 on 2026-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name', 'country'], name='organizatio_name_e27134_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_organization_name_per_country'),
        ),
    ]
