# Generated by Django 4.2.27 on 2026-03-22 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sysadmin', '0003_aiworkflow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_alter_membership_preferred_language'),
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('session_type', models.CharField(choices=[('report_generation', 'Report Generation'), ('project_audit', 'Admin Project Audit')], default='report_generation', max_length=20)),
                ('title', models.CharField(default='New Engineering Report', max_length=255)),
                ('status', models.CharField(choices=[('ingesting', 'Ingesting'), ('interviewing', 'Interviewing'), ('drafting', 'Drafting'), ('review', 'Review'), ('archived', 'Archived')], default='ingesting', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='Primary owner responsible for this session.', on_delete=django.db.models.deletion.CASCADE, related_name='member_sessions', to='organizations.membership')),
                ('organisation', models.ForeignKey(help_text='Organization that owns this session.', on_delete=django.db.models.deletion.CASCADE, related_name='organisation_sessions', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='sysadmin.aiworkflow')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool Call/Result')], max_length=10)),
                ('content', models.TextField(help_text='The raw text of the message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Stores citations, tool names, or UI-specific flags (e.g. { 'task_id': 123 })")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='Primary owner responsible for this session message.', on_delete=django.db.models.deletion.CASCADE, related_name='member_session_messages', to='organizations.membership')),
                ('organisation', models.ForeignKey(help_text='Organization that owns this session massage.', on_delete=django.db.models.deletion.CASCADE, related_name='organisation_session_messages', to='organizations.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.session')),
            ],
            options={
                'db_table': 'session_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
