# Generated by Django 4.2.27 on 2026-04-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_report_reporttask'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.project'),
        ),
    ]
