# Generated by Django 4.2.27 on 2026-07-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('report_generation', 'Report Generation'), ('project_audit', 'Admin Project Audit'), ('requirements', 'Requirements Gathering')], default='report_generation', max_length=20),
        ),
    ]
