# Generated by Django 4.2.27 on 2026-02-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_country_alter_organization_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_organization_name_per_country',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_name_e27134_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
