# Generated by Django 4.2.27 on 2026-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ja', 'Japanese')], default=None, max_length=10, null=True),
        ),
    ]
