# Generated by Django 4.2.27 on 2026-03-22 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_status'),
        ('organizations', '0005_alter_membership_preferred_language'),
        ('chat', '0001_initial'),
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('generated_text', models.TextField(help_text='The actual clean content (Markdown or HTML)')),
                ('structured_data_snapshot', models.JSONField(help_text='The exact technical specs at time of generation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='organizations.membership')),
                ('organisation', models.ForeignKey(help_text='Organization that owns this project.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='projects.project')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='chat.session')),
            ],
            options={
                'db_table': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_validated_by_ai', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(help_text='Organization that owns this report task.', on_delete=django.db.models.deletion.CASCADE, related_name='report_tasks', to='organizations.organization')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_tasks', to='projects.report')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='chat.session')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to='tasks.task')),
            ],
            options={
                'db_table': 'report_tasks',
                'unique_together': {('session', 'task')},
            },
        ),
    ]
