# Generated by Django 4.2.27 on 2026-04-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_membership_preferred_language'),
        ('projects', '0005_report_reporttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.membership'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project'),
        ),
    ]
