# Generated by Django 4.2.27 on 2026-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_report_membership_alter_report_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', help_text='Current lifecycle state of the report (e.g. draft, complete).', max_length=20),
        ),
    ]
