# Generated by Django 4.2.27 on 2026-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('invalid', 'Invalid')], default='draft', help_text='Current lifecycle state of the report (e.g. draft, complete).', max_length=20),
        ),
    ]
