# Generated by Django 4.2.27 on 2026-03-25 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_alter_membership_preferred_language'),
        ('projectMembers', '0002_alter_projectmember_status'),
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectMembers.projectmember')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'db_table': 'task_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['task'], name='task_commen_task_id_4448d0_idx'), models.Index(fields=['organisation'], name='task_commen_organis_cafc71_idx'), models.Index(fields=['created_at'], name='task_commen_created_50c6cd_idx')],
            },
        ),
    ]
