# Generated by Django 4.2.27 on 2026-02-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
