# Generated by Django 4.2.27 on 2026-02-17 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_organization_unique_organization_name_per_country_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Planned end date of the project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for this project.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Human-readable name of the project.', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this project.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='Primary owner responsible for this project.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.membership'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reference',
            field=models.CharField(db_index=True, editable=False, help_text='Short unique reference code for this project (auto-generated).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Planned start date of the project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', help_text='Current lifecycle state of the project (e.g. active, archived, completed).', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('team', 'Team'), ('organisation', 'Organisation')], default='team', help_text='Controls who can see this project (e.g. only team members or entire organization).', max_length=20),
        ),
    ]
