# Generated by Django 4.2.27 on 2026-02-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inactive', 'Inactive'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='pending', help_text='Current lifecycle state of the project (e.g. active, archived, completed).', max_length=20),
        ),
    ]
