# Generated by Django 4.2.27 on 2026-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('review', 'Review'), ('testing', 'Testing'), ('done', 'Done'), ('deployed', 'Deployed'), ('cancelled', 'Cancelled')], default='backlog', max_length=20),
        ),
    ]
