services:
  web_blue:
    build: .
    container_name: web_blue
    ports:
      - "3001:3000"
    env_file:
      - .env.local
    command: sh -c "pnpm start -H 0.0.0.0"

  web_green:
    build: .
    container_name: web_green
    ports:
      - "3002:3000"
    env_file:
      - .env.local
    command: sh -c "pnpm start -H 0.0.0.0"