# Generated by Django 4.2.27 on 2026-03-10 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for this project.', primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Short unique reference code for this project (auto-generated).', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Human-readable name of the project.', max_length=255)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('cohere', 'Cohere'), ('gemini', 'Gemini'), ('local', 'Local')], max_length=50)),
                ('api_key', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted API key for this AI provider', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
