# Generated by Django 4.2.27 on 2026-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'provider'), name='unique_active_ai_model_per_provider'),
        ),
    ]
