# Generated by Django 4.2.27 on 2026-03-11 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sysadmin', '0002_aimodel_unique_active_ai_model_per_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='is_archived')),
                ('is_archived_at', models.DateTimeField(blank=True, null=True, verbose_name='is_archived_at')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='is_deleted_at')),
                ('is_archived_reason', models.TextField(blank=True, default='', verbose_name='is_archived_reason')),
                ('is_deleted_reason', models.TextField(blank=True, default='', verbose_name='is_deleted_reason')),
                ('is_archived_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_archived_by')),
                ('is_deleted_by_email', models.CharField(blank=True, default='', max_length=100, verbose_name='is_deleted_by')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='System-generated unique identifier for this workflow.', primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Short unique reference code for this workflow (auto-generated).', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Human-readable name of the workflow.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what the workflow does.', null=True)),
                ('category', models.CharField(choices=[('requirements', 'Requirements'), ('report', 'Report'), ('translation', 'Translation')], help_text='Workflow category.', max_length=50)),
                ('system_prompt', models.TextField(help_text='System prompt used to instruct the AI model.')),
                ('ai_model', models.ForeignKey(help_text='AI model used to run this workflow.', on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='sysadmin.aimodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Workflow',
                'verbose_name_plural': 'AI Workflows',
                'db_table': 'ai_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='aiworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('category',), name='unique_active_ai_workflow_per_category'),
        ),
    ]
